# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160622_1050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('commentManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
